name: Mirror to Bitbucket

on:
  push:
    branches: [main] # Or other triggers as needed
  schedule:
    - cron: '0 0 */2 * *' # Every 2 days
  workflow_dispatch: # Manual trigger

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Git credentials
        run: |
          git config --global url."https://${{ secrets.BITBUCKET_USERNAME }}:${{ secrets.BITBUCKET_APP_PASSWORD }}@bitbucket.org/".insteadOf "https://bitbucket.org/"

      - name: Push to Bitbucket
        run: |
          REPO_URL="https://bitbucket.org/isaiahcmichael/Ollanect.git" # Public URL directly here
          git remote add bitbucket "$REPO_URL"
          git push --mirror bitbucket